IA/urls.py
from IA import views
from django.urls import path

from IA.views import edit_data_view, delete_data_view, OLSModelDetail, LassoModelDetail, SVMClassificationModelDetail, \
    SVMRegressionModelDetail, KMeansModelDetail

urlpatterns = [
    path("", views.AllMLModels, name="index"),
    path("createModel", views.Createmodel, name="createModel"),
    path("savedModels", views.AllMLModels, name="savedModels"),
    path("trainingData", views.savedTraining.as_view(), name="trainingData"),
    path("trainingData/new", views.NewData, name="trainingData/new"),
    path('trainingData/edit/<int:pk>/', edit_data_view, name='trainingData/editTrainingData'),
    path('delete/', delete_data_view, name='delete_data'),
    path('methods/linear/ols', views.create_ols_model, name='Methods/ols'),
    path('methods/linear/lasso', views.create_lasso_model, name='Methods/lasso'),
    path('methods/svm/classification', views.create_svm_classification_model, name='Methods/classification'),
    path('methods/svm/regression', views.create_svm_regression_model, name='Methods/regression'),
    path('methods/cluster/kmeans', views.create_kmeans_model, name='Methods/kmeans'),
    path('models/linear/ols', views.OLSModels.as_view(), name='models/ols'),
    path('models/ols/<int:pk>/', OLSModelDetail.as_view(), name='ols_model_detail'),
    path('models/linear/lasso', views.LassoModels.as_view(), name='models/lasso'),
    path('models/lasso/<int:pk>/', LassoModelDetail.as_view(), name='lasso_model_detail'),
    path('models/svm/classification', views.SVMClassificationModels.as_view(), name='models/classification'),
    path('models/classification/<int:pk>/', SVMClassificationModelDetail.as_view(), name='classification_model_detail'),
    path('models/svm/regression', views.SVMRegressionModels.as_view(), name='models/regression'),
    path('models/regression/<int:pk>/', SVMRegressionModelDetail.as_view(), name='regression_model_detail'),
    path('models/kmeans', views.KMeansModels.as_view(), name='models/kmeans'),
    path('models/kmeans/<int:pk>/', KMeansModelDetail.as_view(), name='kmeans_model_detail'),
]

IAService/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("", include("IA.urls")),
    path("admin/", admin.site.urls),
]

IA/models.py
from django.db import models


# Create your models here.

class SavedTrainingData(models.Model):
    name = models.CharField(max_length=100)
    values = models.TextField()

    def __str__(self):
        return self.name


class SavedModelsOLS(models.Model):
    name = models.CharField(max_length=100)
    plot = models.ImageField(upload_to='static/ols/', null=True, blank=True)
    endpoint = models.CharField(max_length=400)
    values = models.TextField()

    def __str__(self):
        return self.name


class SavedModelsLasso(models.Model):
    name = models.CharField(max_length=100)
    plot = models.ImageField(upload_to='static/lasso/', null=True, blank=True)
    endpoint = models.CharField(max_length=400)
    values = models.TextField()

    def __str__(self):
        return self.name


class SavedModelsSVMClassification(models.Model):
    name = models.CharField(max_length=100)
    plot = models.ImageField(upload_to='static/svm_classification/', null=True, blank=True)
    endpoint = models.CharField(max_length=400)
    values = models.TextField()

    def __str__(self):
        return self.name


class SavedModelsSVMRegression(models.Model):
    name = models.CharField(max_length=100)
    plot = models.ImageField(upload_to='static/svm_regression/', null=True, blank=True)
    endpoint = models.CharField(max_length=400)
    values = models.TextField()

    def __str__(self):
        return self.name


class SavedModelsKMeans(models.Model):
    name = models.CharField(max_length=100)
    plot = models.ImageField(upload_to='static/kmeans/', null=True, blank=True)
    datasets = models.ManyToManyField(SavedTrainingData)
    endpoint = models.CharField(max_length=400)
    values = models.TextField()

    def __str__(self):
        return self.name

templates/trainingData/editTrainingData.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <div class="container">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <img class="bi me-2" width="150" height="32" src="{% static 'img/auroral.png' %}" alt=""/>
        <span class="fs-4">IA Service</span>
      </a>
      <ul class="nav nav-pills">
        <li class="nav-item"><a href='{% url "index" %}' class="nav-link">Home</a></li>
        <li class="nav-item"><a href='{% url "createModel" %}' class="nav-link">Create model</a></li>
        <li class="nav-item"><a href='{% url "savedModels" %}' class="nav-link">Saved models</a></li>
        <li class="nav-item"><a href='{% url "trainingData" %}' class="nav-link active" aria-current="page">Training data</a></li>
      </ul>
    </header>
    
    <h1>All training data:</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save changes</button>
    </form>

  <footer class="py-3 my-4">
      <ul class="nav justify-content-center border-bottom pb-3 mb-3"></ul>
      <p class="text-center text-body-secondary">© 2023 Universidad Politécnica de Madrid</p>
  </footer>
</div>
</body>


</html>

templates/trainingData/new.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <div class="container">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="/savedModels" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <img class="bi me-2" width="150" height="32" src="{% static 'img/auroral.png' %}" alt=""/>
        <span class="fs-4">AI Service</span>
      </a>
      <ul class="nav nav-pills">
        <li class="nav-item"><a href='{% url "trainingData" %}' class="nav-link active" aria-current="page">Training data</a></li>
        <li class="nav-item"><a href='{% url "createModel" %}' class="nav-link">Execute model</a></li>
        <li class="nav-item"><a href='{% url "savedModels" %}' class="nav-link">Model executions</a></li>
      </ul>
    </header>
    
    <h1>All training data:</h1>
<form method="post" class="mt-3" enctype="multipart/form-data">
    {% csrf_token %}
    
    <div class="form-group">
        <label for="id_name">Name:</label>
        {{ form.name }}
    </div>

    <div class="form-group" id="values_field">
        <label for="id_values">Manual values (Option 1):</label>
        {{ form.values }}
    </div>
    
    <label for="csv_url">KGB URL data (Option 2):</label>
    <input type="url" id="csv_url" name="csv_url" class="form-control">

    <label for="csv_file">Load CSV file (Option 3):</label>
    <input type="file" id="csv_file" name="csv_file" class="form-control">

    <label for="column_choice">Choose CSV column:</label>
    <select id="column_choice" name="column_choice" class="form-control"></select>

    <button type="submit" class="btn btn-primary">Save</button>
</form>

  <footer class="py-3 my-4">
      <ul class="nav justify-content-center border-bottom pb-3 mb-3"></ul>
      <p class="text-center text-body-secondary">© 2023 Universidad Politécnica de Madrid</p>
  </footer>
</div>
</body>
<script>
    document.getElementById('csv_file').addEventListener('change', function(event) {
        var file = event.target.files[0];
        var reader = new FileReader();
        reader.onload = function(e) {
            var text = e.target.result;
            var lines = text.split('\n');
            var headers = lines[0].split(',');
            var select = document.getElementById('column_choice');
            select.innerHTML = '';
            headers.forEach(function(header, index) {
                var option = document.createElement('option');
                option.value = index;
                option.textContent = header;
                select.appendChild(option);
            });
            document.getElementById('id_values').style.display = file ? 'none' : 'block';
        };
        reader.readAsText(file);
    });
</script>

</html>